"""adds CountdownEvent model

Revision ID: 414c79d7a694
Revises: 
Create Date: 2021-07-04 23:31:54.946650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414c79d7a694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countdown_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('countdown_till_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countdown_event')
    # ### end Alembic commands ###
