"""empty message

Revision ID: 8629dc2b8fd4
Revises: 6be16609412b
Create Date: 2021-07-19 17:55:08.587868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8629dc2b8fd4'
down_revision = '6be16609412b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countdown_event', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countdown_event', 'creation_date')
    # ### end Alembic commands ###
