"""empty message

Revision ID: c4566b99e5db
Revises: c474ff8ae24e
Create Date: 2021-07-19 22:13:02.766066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4566b99e5db'
down_revision = 'c474ff8ae24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countdown_event', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'countdown_event', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countdown_event', type_='foreignkey')
    op.drop_column('countdown_event', 'user_id')
    # ### end Alembic commands ###
